### PR TITLE
fix: inline code blocks

### PR DESCRIPTION
**Pull request by uncenter**
Upstreams https://github.com/catppuccin/userstyles/pull/1002.

### CODE REVIEW

**Comment by splashsky** [comment]
Can we get this merged? I'm having issues with inline code blocks in my personal repos as well 😛 

image

**Comment by uncenter** [comment]
> Can we get this merged? I'm having issues with inline code blocks in my personal repos as well 😛
> 
> image

Uhh that screenshot isn't what this fixes afaik? This is meant to fix code blocks with accent colored backgrounds, which you can see in https://github.com/catppuccin/userstyles/pull/1002.

**Comment by splashsky** [comment]
Ah shoot. Well I'll file another issue then 🤣

**Comment by uncenter** [comment]
> Can we get this merged? I'm having issues with inline code blocks in my personal repos as well 😛
> 
> image

Can you send a link to that repo? I can make a fix.

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
